### PR TITLE
Fix mesh displacement material setting

### PR DESCRIPTION
**Pull request by hshakula**
Displacement material relies on the mesh subdivision factor. Whenever the subdivision factor is 0 we need to unset displacement material and vice versa if the subdivision factor is greater than 0 we should set displacement material.

### CODE REVIEW

**Comment by bsavery** [comment]
Just a question here.  Why do we *NEED* to unset displacement if subdivision is 0?  Would it make more sense to add subdivision factor automatically if displacement is set?

**Comment by hshakula** [comment]
> Why do we NEED to unset displacement if subdivision is 0?

[RPR docs](https://radeon-pro.github.io/RadeonProRenderDocs/sdk/api/rprshapesetdisplacementmaterial.html) saying that subdivision is required for displacement to work. When I have been setting displacement to meshes without subdivision rprContextRender was not rendering anything without any errors. As soon as I unset displacement it would work as before.

> Would it make more sense to add subdivision factor automatically if displacement is set?

'Explicit is better than implicit' (c)
So I thought it would be better to ignore displacement on non-subdivision surfaces. And otherwise, if we would enable implicit subdivision, what subdivision level should we set?

**Comment by bsavery** [comment]
Generally I agree in the explicit is better than implicit.  However in this case the end effect is no displacement when the user is expecting it.  So either way the behavior is unexpected for the user.  

My recommendation would be to implicitly add subdivision if displacement is set.

**Comment by hshakula** [comment]
It makes sense for me, I agree. I will rewrite it in such a way that when the displacement is used without subdivision then it will force subdivision with refine level equal to 1. In such case, the user will see at least something, probably not perfect displacement but some low poly version of it, which should reveal the right direction to solve this issue - increase subdivision level

**Comment by bsavery** [comment]
Agreed

**Comment by hshakula** [comment]
Okay, I made it in such a way that it will try to set subdivision factor to 1 and only if it succeeds displacement material will be set

**Pull request merged**
