### PR TITLE
uber emission color intensity

### PR DESCRIPTION
**Pull request by dmitrii-z**
### PURPOSE
Resolves https://amdrender.atlassian.net/browse/RPRHOUD-66

### TECHNICAL STEPS
The intensity implementation is that the emission color should be multiplied by the intensity value (that's how it works in Blender plugin
To get this, BaseNode is extended with a class for the Uber node that adds an extra multiply node before the actual emission color node and redirects Uber's emission color and intensity inputs to this node.

### CODE REVIEW

**Review by ARozghon — APPROVED** [review]
Approved by QA

**Comment by bsavery** [comment]
How is an intensity different than the weight.  Internally they should be the same inside Uber.

**Comment by dmitrii-z** [comment]
> How is an intensity different than the weight. Internally they should be the same inside Uber.

I took the blender plugin as an example. There, the weight is used to assign MATERIAL_INPUT_UBER_EMISSION_WEIGHT, and intensity is multiplied by color to get the final color. So, weight shows how strong the emission is, and intensity how bright its color is. Should it behave another way?

**Comment by ARozghon** [comment]
weight - it's for Emissive texture maps and intensity - for more emission power, we have the same option in Uber for the Blender Plugin

**Review by V-Gorash — APPROVED** [review]

**Review by bsavery — APPROVED** [review]

**Pull request merged**
