### PR TITLE
Enabling Sphere light support for HybridPro

### PR DESCRIPTION
**Pull request by bnagirniak**
### PURPOSE
HybridPro supports rprContextCreateSphereLight().

### EFFECT OF CHANGE
Enabled HdRPR to craete Sphere light instead of box which is a workaround.

### TECHNICAL STEPS
Enabled IsSphereAndDiskLightSupported() for HybridPro either.

### CODE REVIEW

**Comment by hshakula** [comment]
What about a disk light, does it work in HybridPro? If not, we should split the `IsSphereAndDiskLightSupported` into two separate functions.

**Comment by bnagirniak** [comment]
I'll check this

**Comment by bnagirniak** [comment]
> What about a disk light, does it work in HybridPro? If not, we should split the `IsSphereAndDiskLightSupported` into two separate functions.

Checked, disk light is also supported in HybridPro.

**Review by hshakula — APPROVED** [review]

**Review by DagerD — APPROVED** [review]
Tested. Works ok.

**Pull request merged**
