### PR TITLE
improve performance for multicore and multithread (SMT) CPUs

### PR DESCRIPTION
**Pull request by sidietz**
### PURPOSE
Performance optimization for zen2+ and bulldozer arch.

### EFFECT OF CHANGE
nothing.

### TECHNICAL STEPS
nothing.

### NOTES FOR REVIEWERS
Someone may display a warning that this optimization does not work on Haswell, IvyBridge and Intel (R) archs before GerminiLake.

### CODE REVIEW

**Comment by hshakula** [comment]
We have only 4 submodules. Could you please elaborate on why do we need to force everyone to setup 64 workers to just fetch 4 submodules?

git docs:
> -j <n>
--jobs <n>
    The number of submodules fetched at the same time. Defaults to the submodule.fetchJobs option.

Anyone who would customize the number of jobs already knows what he/she does and these numbers don't make sense to them.

@bsavery, thoughts?

**Comment by bsavery** [comment]
Yeah, I agree with what @hshakula said.  -j4 is probably enough  Also I'm not sure how heavy IO tasks like git submodule always are the most efficient with high worker numbers but I could be wrong.

@sidietz Appreciate the contribution!  The changes here seems like it's not Zen specific, maybe change the titled?

**Comment by sidietz** [comment]
Lets assume a non-real high-throughput SMT server with the following configuration:
64 cores, SMT2 (meaning 2 threads per core) resulting in 128 Threads in an 2HE 19 inch Rack with NVMe SSDs as primary disks.

That system should be able to handle -j 64. -j - as far as I know - does not only parallelize submodules. I think in the most recent git version it parallelizes the download streams, too.

However for legacy systems (less than 4 cores with 8 threads) another switch (like -j 8) should be considered valid.

**Comment by bsavery** [comment]
> I think in the most recent git version it parallelizes the download streams, too.

Did you find any documentation of this?  I haven't seen that.  Interesting.

**Comment by d-croft** [comment]
> > I think in the most recent git version it parallelizes the download streams, too.
> 
> Did you find any documentation of this? I haven't seen that. Interesting.

After having checked the doc you seem to be right.

**Comment by bsavery** [comment]
Ah I realized this was for master after I merged it @d-croft in the future we do PR's to develop and then i merge to master when we bump the version.  So just do yours to develop please!

**Pull request merged**
