### PR TITLE
mtlx editing

### PR DESCRIPTION
**Pull request by dmitrii-z**
### PURPOSE
Resolves: https://amdrender.atlassian.net/browse/RPRHOUD-69
When the material is imported, the script parses the MaterialX file and generates a graph of MaterialX nodes related to the material.
A graph is placed into the newly created library when the material is imported on a state level, or into a subnet when imported on the library/subnet level.
Also added sorting for material/category lists and hashing for the faster import window opening.

### CODE REVIEW

**Review by ARozghon — COMMENTED** [review]
need to make some tweaks, because now the subnet has a lot of conflicts if try to import more than one material to the material library node

**Review by ARozghon — APPROVED** [review]
Approved by QA

**Comment by bsavery** [comment]
Please add more description to the Pull Request.

**Comment by ARozghon** [comment]
This pull request is for the Web Material Library import to Houdini, into the previous iteration all materials were imported as RPRmaterials, and now - imported as MaterialX files.

**Review by bsavery — APPROVED** [review]

**Pull request merged**
