### PR TITLE
Replace bilateral and EAW filters with AI Denoiser

### PR DESCRIPTION
**Pull request by hshakula**

### CODE REVIEW

**Comment by bsavery** [comment]
So I don't have time to track this down right now, but this (and master branch) gives an error on macOS "Unable to create RIF context".  Not sure if you have a macOS system

**Comment by bsavery** [comment]
Couple issues I see here:  

1.  We need this to link against https://www.amd.com/en/technologies/sdk-agreement the RIF library here.  

2.   The "OpenImage" denoise libraries are not included there.  So I'm not sure that will be an option.  Maybe us EAW if no option to use AI?

3.  MiOpen is included on linux as well

**Comment by hshakula** [comment]
Remove all references to OpenImage denoiser, EAW used on CPU-win and CPU-GPU-mac

**Comment by hshakula** [comment]
I've removed all references to OpenImage denoiser, and now EAW used on CPU-win and CPU-GPU-mac

**Comment by bsavery** [comment]
Looks good.

**Pull request merged**
